### Nama      : Teguh Dwi Julyanto
### NIM       : F1D022098
### No. Absen : 19
### Kelas     : C

$$
\overset{\text{Data Training}}{\begin{bmatrix}
1 & -1 & -1 & -1 & 1 & -1 & 1 \\
-1 & 1 & 1 & 1 & 1 & -1 & -1 \\
-1 & -1 & 1 & -1 & -1 & 1 & 1 \\
-1 & -1 & 1 & -1 & 1 & -1 & 1 \\
-1 & 1 & -1 & -1 & -1 & 1 & 1 \\
1 & -1 & 1 & -1 & 1 & 1 & 1 \\
-1 & -1 & 1 & 1 & -1 & -1 & -1 \\
-1 & 1 & -1 & 1 & -1 & -1 & -1 \\
1 & -1 & -1 & 1 & -1 & 1 & -1 \\
-1 & 1 & 1 & 1 & 1 & 1 & -1
\end{bmatrix}}
$$

$$
\overset{\text{Training Label}}{\begin{bmatrix}
A & B & A & A & A & A & B & B & B & B
\end{bmatrix}}
$$

$$
\overset{\text{Data Testing } (X_U)}{
\begin{bmatrix}
1 & -1 & -1 & -1 & 1 & -1 & 1 \\
-1 & -1 & 1 & -1 & -1 & 1 & 1 \\
-1 & -1 & 1 & -1 & 1 & -1 & 1 \\
1 & -1 & -1 & 1 & -1 & 1 & -1 \\
1 & 1 & 1 & -1 & 1 & 1 & 1
\end{bmatrix}
}
$$

$$
\overset{\text{Testing Label}}{
\begin{bmatrix}
A & A & A & B & B
\end{bmatrix}
}
$$


### **1. Model HAM**

#### **Inisialisasi Data**

- **X_Tr** → Data training yang berisikan pola-pola input dalam bentuk bipolar
- **Class_Tr** → Label dari tiap pola training 
- **X_U** → Data testing
- **Class_U** → Label sebenarnya dari data testing


#### **Konversi label ke bentuk bipolar**

- **A** → [1,-1]
- **B** → [-1,1]



#### **Perhitungan bobot**

$$
W = X_{\text{Tr}}^{T} \times Y_{\text{Tr}}
$$

Keterangan:


\begin{aligned}
W & : \text{Matriks bobot hasil pelatihan} \\
X_{\text{Tr}} & : \text{Matriks input data training} \\
X_{\text{Tr}}^{T} & : \text{Transpose dari matriks input training} \\
Y_{\text{Tr}} & : \text{Matriks target bipolar dari label training}
\end{aligned}



#### **Fungsi AKtivasi**

$$
f(y_{\text{in}}) =
\begin{cases}
1, & \text{jika } y_{\text{in}} > 0 \\
-1, & \text{jika } y_{\text{in}} \le 0
\end{cases}
$$

#### **Menghitung Output untuk Data Uji**

$$
Y_{\text{in}} = X_{U} \times W
$$

$$
Y_{\text{out}} = f(Y_{\text{in}})
$$

In [2]:
import numpy as np

X_Tr = np.array([
    [1, -1, -1, -1, 1, -1, 1],
    [-1, 1, 1, 1, 1, -1, -1],
    [-1, -1, 1, -1, -1, 1, 1],
    [-1, -1, 1, -1, 1, -1, 1],
    [-1, 1, -1, -1, -1, 1, 1],
    [1, -1, 1, -1, 1, 1, 1],
    [-1, -1, 1, 1, -1, -1, -1],
    [-1, 1, -1, 1, -1, -1, -1],
    [1, -1, -1, 1, -1, 1, -1],
    [-1, 1, 1, 1, 1, 1, -1]
])

Class_Tr = ['A', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B']

X_U = np.array([
    [1, -1, -1, -1, 1, -1, 1],
    [-1, -1, 1, -1, -1, 1, 1],
    [-1, -1, 1, -1, 1, -1, 1],
    [1, -1, -1, 1, -1, 1, -1],
    [1, 1, 1, -1, 1, 1, 1]
])

Class_U = ['A', 'A', 'A', 'B', 'B']

target_map = {
    'A': np.array([1, -1]),
    'B': np.array([-1, 1])
}
Y_Tr = np.array([target_map[label] for label in Class_Tr])

W = X_Tr.T @ Y_Tr

print("============== Fase Training ==============")
print("Matriks Bobot (W) shape:", W.shape)
print("Matriks Bobot W:\n", W)
print("")

def activation(y_in):
    return np.where(y_in > 0, 1, -1)

Y_in_U = X_U @ W
Y_out_U = activation(Y_in_U)

print("============== Fase Testing ==============")
print("Net Input (Y_in_U):\n", Y_in_U)
print("\nOutput Bipolar (Y_out_U):\n", Y_out_U)
print("")

reverse_target_map = {tuple(v): k for k, v in target_map.items()}

predictions = []
for y_vec in Y_out_U:
    y_tuple = tuple(y_vec)
    predicted_class = reverse_target_map.get(y_tuple, 'Unknown')
    predictions.append(predicted_class)

print("============== Hasil Prediksi ==============")
for i in range(len(X_U)):
    print(f"Pola ke-{i+1}: {X_U[i]} -> Prediksi: {predictions[i]} | Label Asli: {Class_U[i]}")

correct = sum(p == t for p, t in zip(predictions, Class_U))
accuracy = correct / len(Class_U) * 100

print("\n============== Evaluasi ==============")
print(f"Total Benar: {correct}/{len(Class_U)}")
print(f"Akurasi: {accuracy:.2f}%")
print("")


============== Fase Training ==============
Matriks Bobot (W) shape: (7, 2)
Matriks Bobot W:
 [[  2  -2]
 [ -4   4]
 [  0   0]
 [-10  10]
 [  2  -2]
 [  2  -2]
 [ 10 -10]]

============== Fase Testing ==============
Net Input (Y_in_U):
 [[ 26 -26]
 [ 22 -22]
 [ 22 -22]
 [-14  14]
 [ 22 -22]]

Output Bipolar (Y_out_U):
 [[ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [-1  1]
 [ 1 -1]]

============== Hasil Prediksi ==============
Pola ke-1: [ 1 -1 -1 -1  1 -1  1] -> Prediksi: A | Label Asli: A
Pola ke-2: [-1 -1  1 -1 -1  1  1] -> Prediksi: A | Label Asli: A
Pola ke-3: [-1 -1  1 -1  1 -1  1] -> Prediksi: A | Label Asli: A
Pola ke-4: [ 1 -1 -1  1 -1  1 -1] -> Prediksi: B | Label Asli: B
Pola ke-5: [ 1  1  1 -1  1  1  1] -> Prediksi: A | Label Asli: B

============== Evaluasi ==============
Total Benar: 4/5
Akurasi: 80.00%



### **2. Model LVQ**

#### **Inisialisasi Data**

- **X_Tr** → Data training yang berisikan pola-pola input dalam bentuk bipolar
- **Class_Tr** → Label dari tiap pola training 
- **X_U** → Data testing
- **Class_U** → Label sebenarnya dari data testing


#### **Inisialisasi Prototype**

- **proto_A** → X_Tr[0]
- **proto_B** → X_Tr[1]

$$
\mathbf{W} = 
\begin{bmatrix}
\mathbf{w}_A \\
\mathbf{w}_B
\end{bmatrix}
$$


\begin{aligned}
W_{\text{A}} & = X_{\text{Tr}}^{(A)} & {\text{Dan   }} & W_{\text{B}} & = X_{\text{Tr}}^{(B)} \\
\end{aligned}

#### **Parameter Learning**

- learning_rate = 0.1
- epochs = 50
- decay_rate = 0.99

#### **Hitung Jarak**

$$
d(x, w_i) = \sqrt{\sum_{j=1}^{n} (x_j - w_{ij})^2}
$$


#### **Training**

$$
\mathbf{w}_c^{(t+1)} =
\begin{cases}
\mathbf{w}_c^{(t)} + \alpha \, (\mathbf{x} - \mathbf{w}_c^{(t)}), & \text{jika } \text{kelas cocok} \\
\mathbf{w}_c^{(t)} - \alpha \, (\mathbf{x} - \mathbf{w}_c^{(t)}), & \text{jika } \text{kelas tidak cocok}
\end{cases}
$$


#### **Testing**

$$
\hat{y} = \arg\min_i \, d(x_u, w_i)
$$


In [ ]:
import numpy as np

X_Tr = np.array([
    [1, -1, -1, -1, 1, -1, 1],   
    [-1, 1, 1, 1, 1, -1, -1],   
    [-1, -1, 1, -1, -1, 1, 1],   
    [-1, -1, 1, -1, 1, -1, 1],   
    [-1, 1, -1, -1, -1, 1, 1],   
    [1, -1, 1, -1, 1, 1, 1],    
    [-1, -1, 1, 1, -1, -1, -1],  
    [-1, 1, -1, 1, -1, -1, -1],  
    [1, -1, -1, 1, -1, 1, -1],   
    [-1, 1, 1, 1, 1, 1, -1]     
])

Class_Tr = ['A', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B']

X_U = np.array([
    [1, -1, -1, -1, 1, -1, 1],   
    [-1, -1, 1, -1, -1, 1, 1],   
    [-1, -1, 1, -1, 1, -1, 1],   
    [1, -1, -1, 1, -1, 1, -1],   
    [1, 1, 1, -1, 1, 1, 1]      
])

Class_U = ['A', 'A', 'A', 'B', 'B']

proto_A = X_Tr[0].copy().astype(float)
proto_B = X_Tr[1].copy().astype(float)
prototypes = np.array([proto_A, proto_B])
proto_labels = ['A', 'B']

learning_rate = 0.1
epochs = 50
decay_rate = 0.99

print("============== Inisialisasi ==============")
print(f"Prototype awal 'A':\n {prototypes[0]}")
print(f"Prototype awal 'B':\n {prototypes[1]}")
print(f"Learning Rate awal: {learning_rate}, Epochs: {epochs}")
print("")

def euclidean_distance(v1, v2):
    return np.linalg.norm(v1 - v2)

for epoch in range(epochs):
    for i in range(len(X_Tr)):
        x = X_Tr[i]
        y_true = Class_Tr[i]
        distances = [euclidean_distance(x, p) for p in prototypes]
        winner_idx = np.argmin(distances)
        winner_label = proto_labels[winner_idx]
        winner_vec = prototypes[winner_idx]

        if y_true == winner_label:
            prototypes[winner_idx] += learning_rate * (x - winner_vec)
        else:
            prototypes[winner_idx] -= learning_rate * (x - winner_vec)

    learning_rate *= decay_rate

print("============== Fase Training ==============")
print(f"Learning Rate akhir: {learning_rate:.6f}")
print(f"Prototype 'A' (setelah train):\n {np.round(prototypes[0], 4)}")
print(f"Prototype 'B' (setelah train):\n {np.round(prototypes[1], 4)}")
print("")

def predict_lvq(x_unknown, prototypes, proto_labels):
    distances = [euclidean_distance(x_unknown, p) for p in prototypes]
    winner_idx = np.argmin(distances)
    return proto_labels[winner_idx]

predictions = [predict_lvq(x, prototypes, proto_labels) for x in X_U]

print("============== Hasil Prediksi ==============")
for i in range(len(X_U)):
    print(f"Pola ke-{i+1}: {X_U[i]} -> Prediksi: {predictions[i]} | Label Asli: {Class_U[i]}")


correct = sum(p == t for p, t in zip(predictions, Class_U))
accuracy = correct / len(Class_U) * 100

print("\n============== Evaluasi ==============")
print(f"Total Benar: {correct}/{len(Class_U)}")
print(f"Akurasi: {accuracy:.2f}%")
print("")